---

- block:
  - name: clear the existing /tmp dir (1/5)
    shell: "/bin/rm -rf *"
    args:
      chdir: /tmp
    #warn: false

  - name: copy systemd file (2/5)
    copy:
      src: /usr/share/systemd/tmp.mount
      dest: /lib/systemd/system/tmp.mount
      remote_src: True

  - name: create dir /etc/systemd/system/tmp.mount.d (3/5)
    file:
      path: /etc/systemd/system/tmp.mount.d
      state: directory

  - name: create tmp.mount custom options file (4/5)
    copy:
      dest: /etc/systemd/system/tmp.mount.d/options.conf
      content: |
        [Mount]
        Options=mode=1777,strictatime,nosuid,nodev,size=512M
  - name: start and enable tmp.mount on boot (5/5)
    systemd:
      name: tmp.mount
      enabled: yes
      state: started
      daemon_reload: yes

- name: disable system crash reports
  lineinfile:
    dest: /etc/default/apport
    regexp: "^enabled=(0|1)"
    line: enabled=0
    state: present
- name: tune system swap
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
- name: perform dist upgrade
  apt:
    update_cache: yes
    upgrade: dist
- name: install archiving tools
  apt: 
    name: "{{ base_archiving_tools }}"
    state: present
- name: install system tools
  apt:
    name: "{{ base_sys_tools }}"
    state: present
- name: install system tools for laptop
  apt:
    name: "{{ base_system_tools_laptop }}"
    state: present
  when: laptop_mode
- name: install developer tools
  apt:
    name: "{{ base_developer_tools }}"
    state: present
- name: install media packages
  apt:
    name: "{{ base_media_tools }}"
    state: present

...
